[package]
name = "esl"
version = "0.1.0"
authors = ["Ari Seyhun <ariseyhun@live.com.au>"]
edition = "2021"
description = "Event-sourcing Schema Language parser"
repository = "https://github.com/thalo-rs/esl"
license = "MIT OR Apache-2.0"
keywords = ["event-sourcing", "cqrs", "event-driven", "schema"]
categories = ["data-structures", "development-tools", "rust-patterns"]

[dependencies]
nom = { version = "7.1", features = ["alloc"] }
nom-supreme = "0.6"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[features]
default = []
codegen = []
