[package]
name = "esdl"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7.1", features = ["alloc"] }
nom-supreme = "0.6"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[features]
default = []
codegen = []
